import { ArrowLeft, Braces, Clock3, GitCompare, History, Play } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useStartRun, useWorkflow } from '../api/hooks'
import { ErrorState, PageHeader, Panel } from '../components/Page'
import { WorkflowGraph } from '../components/WorkflowGraph'

export default function WorkflowDetailPage() {
  const { workflowId } = useParams(); const workflow = useWorkflow(workflowId); const start = useStartRun(); const navigate = useNavigate()
  if (workflow.isLoading) return <div className="detail-skeleton" />
  if (workflow.isError || !workflow.data) return <ErrorState error={workflow.error} retry={() => workflow.refetch()} />
  const run = async () => { const value = await start.mutateAsync({ workflowId: workflow.data.id }); navigate(`/console/executions/${value.id}`) }
  return <>
    <Link className="back-link" to="/console/workflows"><ArrowLeft size={15}/>Workflows</Link>
    <PageHeader eyebrow={`Version ${workflow.data.version}`} title={workflow.data.name} description={`${workflow.data.taskCount} tasks across ${workflow.data.executionLevels.length} execution levels.`} actions={<><Link className="button secondary" to={`/console/workflows/new?from=${workflow.data.id}`}><GitCompare size={16}/>Edit as new version</Link><button className="button primary" onClick={run} disabled={start.isPending}><Play size={16}/>Run workflow</button></>} />
    <div className="detail-stats"><div><Braces/><strong>{workflow.data.taskCount}</strong><span>Tasks</span></div><div><History/><strong>{workflow.data.version}</strong><span>Current version</span></div><div><Clock3/><strong>{Math.max(...workflow.data.tasks.map((task) => task.timeoutSeconds))}s</strong><span>Longest timeout</span></div></div>
    <Panel title="Compiled execution graph" description="Dependency order generated by the backend workflow compiler"><WorkflowGraph tasks={workflow.data.tasks} height={500}/></Panel>
    <div className="two-column-panels"><Panel title="Execution levels" description="Tasks in the same level may run concurrently"><div className="levels-list">{workflow.data.executionLevels.map((level, index) => <div key={index}><span>Level {index + 1}</span><div>{level.map((task) => <code key={task}>{task}</code>)}</div></div>)}</div></Panel><Panel title="Definition summary"><dl className="definition-summary"><div><dt>Created</dt><dd>{new Date(workflow.data.createdAt).toLocaleString()}</dd></div><div><dt>Delivery semantics</dt><dd>At least once</dd></div><div><dt>Default retry policy</dt><dd>Per-task attempts</dd></div><div><dt>Control plane</dt><dd>PostgreSQL durable state</dd></div></dl></Panel></div>
  </>
}
